version: '3.7' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 webapp: # name of the first service
  build: front-proy # specify the directory of the Dockerfile
  volumes:
    - '.:/app'
    - '/app/node_modules'
  ports:
    - "8080:8080" # specify port mapping
 
 express: # name of the second service
  build: back-proy # specify the directory of the Dockerfile
  ports:
    - "3000:3000" #specify ports mapping
  links:
    - database # link this service to the database service
 
 database: # name of the third service
  image: mongo # specify image to build container from
  ports:
    - "27017:27017" # specify port forwarding